@startuml OAuth Client Credentials Flow
    skinparam maxMessageSize 110
    skinparam sequenceMessageAlign center

    App -> OAuth : ClientId & Secret
    OAuth -> OAuth : Validate ClientID & Secret
    App <-- OAuth : accessToken
    App -> Resource : request(accessToken)
    Resource -> Resource : Validate accessToken
    Resource --> App : response

@enduml